### ISSUE TITLE
Map copy error

### ISSUE THREAD

**Issue by hlherrera** [pagameba/node-mapserver#3]
I'm trying to run an example mapserv.js, but I have this error:
var map = maps[page].copy();
                           ^
TypeError: Object #<Map> has no method 'copy'

Then I remove copy method of Map object, ->  var map = maps[page] 
And this work OK in a single request, but when I do multiple request(using tiles) I have an core violation segment error.
Error in `nodejs': double free or corruption (out): 0xa1b0b070

I suppose that I need to clone the map object, but how ? Can you help me?

**Comment by pagameba** [comment]
No feedback, assuming this is working.
